name: PR to Telegram
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          debug: true
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Nieuwe pull request bij de Snor lijsten. Even checken&#58; https://github.com/geensnor/SnorLijsten/pulls
